version: '3.8'

networks:
  network:
    driver: bridge

services:
  nexus_server:
    build: ./app
    container_name: nexus_server_container
    expose:
      - 5000
    networks:
      - network

  nginx:
    image: nginx:alpine
    container_name: nexus_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nexus_server
    networks:
      - network