version: '3.8'

networks:
  network:
    driver: bridge

services:
  nexus_server:
    build: ./app
    container_name: nexus_server_container
    expose:
      - 5000
    networks:
      - network

  caddy:
    image: caddy:2-alpine
    container_name: nexus_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - nexus_server
    networks:
      - network